// Single source of truth for faculty records.
// Imported by both prisma/seed.ts (full DB seed) and prisma/update-faculty.ts
// (faculty-only sync that leaves applications/programs/events untouched).

export const FACULTY = [
  // ── Directors & Principals (Administration) ──────────────────────────────
  { name: "Dr. Rooh ul Husnain Khizar", title: "Project Director",              department: "Administration", bio: "Dr. Rooh ul Husnain Khizar serves as Project Director of Riphah International College, providing strategic vision and leadership to drive institutional excellence and academic growth.", specializations: ["Institutional Leadership","Strategic Planning","Academic Development"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/Dr Rooh ul husnain khizar.jpeg", isDirector: true,  displayOrder: 1 },
  { name: "Muhammad Shahbaz",           title: "Chairperson",                   department: "Administration", bio: "Muhammad Shahbaz is the Chairperson of Riphah International College, overseeing governance, institutional policy, and the overall direction of the college's academic and operational affairs.", specializations: ["Governance","Institutional Policy","Administration"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/Muhammad Ayaz Shahbaz.jpeg", isDirector: true,  displayOrder: 2 },
  { name: "Dr. Arslan Iqbal",           title: "Director of Accounts & Finance", department: "Finance",       bio: "Dr. Arslan Iqbal heads the Accounts and Finance department, bringing deep expertise in financial management, institutional budgeting, and fiscal planning to ensure the college's financial health.", specializations: ["Financial Management","Budgeting","Accounting","Fiscal Planning"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/dr-arslan-iqbal.png", isDirector: true,  displayOrder: 3 },
  { name: "Muhammad Ayaz",              title: "Director — Information Technology", department: "Administration", bio: "Muhammad Ayaz brings an international academic background from Australia, holding a Bachelor of Information Systems (Business & Systems Analyst), a Professional Year in Information Systems, a Diploma in Information Technology, and a Postgraduate Diploma in Teaching. As Director of Information Technology, he combines strong expertise in information systems and business analysis with formal training in modern pedagogy to advance the college's digital infrastructure and technology-driven learning.", specializations: ["Information Systems","Business & Systems Analysis","Information Technology","Teaching & Pedagogy"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/muhammad-ayaz.jpeg", isDirector: true,  displayOrder: 4 },

  // ── Faculty Members ──────────────────────────────────────────────────────
  { name: "Dr. Behzad Hussain", title: "Assistant Professor — Biology", department: "Science", bio: "An accomplished microbiologist and award-winning PhD researcher with 8+ years of academic excellence. He specializes in molecular virology, viral immunology, and cancer immunotherapy, with multidisciplinary expertise across proteomics and bioinformatics.", specializations: ["Molecular Virology","Viral Immunology","Proteomics","Bioinformatics","Cancer Immunotherapy"], publications: 0, awards: 2, students: 0, image: "/uploads/faculty/behzad-hussain.jpeg", isDirector: false, displayOrder: 5 },
  { name: "Muhammad Saeed", title: "HOD — Physics & Discipline Head", department: "Science", bio: "An accomplished Physics educator and academic leader with over a decade of teaching experience. As Head of Department and Discipline Head, he combines academic rigor with strong administrative leadership and engaging, practical instruction.", specializations: ["Physics","Mechanics","Electromagnetism","Lab Demonstrations","Academic Administration"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/muhammad-saeed.png", isDirector: false, displayOrder: 6 },
  { name: "Qasim Munir Lodhi", title: "Lecturer — Mathematics", department: "Mathematics", bio: "A dedicated mathematics educator with 5+ years of proven teaching excellence at reputable institutions. A former Controller of Examinations, he specializes in secondary and higher secondary mathematics and structured, achievement-focused learning.", specializations: ["Secondary Mathematics","Higher Secondary Math","Calculus","Examination Management"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/qasim-munir-lodhi.png", isDirector: false, displayOrder: 7 },
  { name: "Prof. Aasma Khushi", title: "Lecturer — Urdu & PhD Scholar", department: "Languages", bio: "A distinguished Urdu scholar and Gold Medalist with 12+ years of teaching experience and an active PhD scholar. She blends linguistic expertise, technological proficiency, and creative arts skills into a comprehensive, research-driven approach.", specializations: ["Urdu Literature","Linguistics","Creative Arts","Computer Skills","Research"], publications: 0, awards: 1, students: 0, image: "/uploads/faculty/aasma-khushi.jpeg", isDirector: false, displayOrder: 8 },
  { name: "Prof. Muhammad Usman", title: "HOD — Commerce", department: "Commerce", bio: "An experienced commerce educator and departmental leader with 12+ years of institutional teaching experience. As Head of Department, he pairs strategic vision with hands-on expertise in business mathematics, accounting, and modern teaching methodologies.", specializations: ["Business Mathematics","Accounting","Commerce","Discipline Management"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/muhammad-usman.png", isDirector: false, displayOrder: 9 },
  { name: "Muhammad Javaid", title: "Lecturer — Economics", department: "Commerce", bio: "An economics educator with 22+ years of diverse experience spanning the Federal Bureau of Statistics and the college classroom. He grounds economic theory in real-world data, contributing deep expertise in quantitative economics and applied research.", specializations: ["Quantitative Economics","Applied Research","Statistics","Economic Policy"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/muhammad-javaid.png", isDirector: false, displayOrder: 10 },
  { name: "Sajid Hameed", title: "HOD — Computer Science", department: "Technology", bio: "An accomplished computer science educator and departmental leader with 12+ years of specialized expertise. With an MSc in Information Technology, he blends deep software engineering knowledge with modern, technology-driven teaching to prepare students for the IT industry.", specializations: ["Software Engineering","Programming","Information Technology","Modern Pedagogy"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/sajid-hameed.png", isDirector: false, displayOrder: 11 },
  { name: "Muhammad Faizan Anwar Cheema", title: "HOD — Islamic Studies", department: "Religious Studies", bio: "A dedicated Islamic scholar and Head of Department specializing in Fiqah (Islamic Jurisprudence) and Hadith. He brings both theological depth and pedagogical effectiveness, with a strong track record of improving student performance.", specializations: ["Fiqah (Jurisprudence)","Hadith Sciences","Islamic Studies","Quran Studies"], publications: 0, awards: 0, students: 0, image: "/uploads/faculty/faizan-anwar-cheema.jpeg", isDirector: false, displayOrder: 12 },
]
